# Generated by Django 4.1.4 on 2022-12-25 00:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Services",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("NETFLIX", "Netflix"),
                            ("AMAZON", "Amazon Video"),
                            ("START", "Start+"),
                            ("PARAMOUNT", "Paramount+"),
                        ],
                        default="NETFLIX",
                        max_length=15,
                    ),
                ),
                ("description", models.TextField()),
                ("logo", models.TextField()),
            ],
            options={
                "db_table": "services",
            },
        ),
        migrations.CreateModel(
            name="Payment_user",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("amount", models.FloatField(default=0.0)),
                ("paymentDate", models.DateField(null=True)),
                ("expirationDate", models.DateField(null=True)),
                (
                    "service_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="pagos.services",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "payment_user",
            },
        ),
        migrations.CreateModel(
            name="Pagos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "servicio",
                    models.CharField(
                        choices=[
                            ("NF", "Netflix"),
                            ("AP", "Amazon Video"),
                            ("ST", "Start+"),
                            ("PM", "Paramount+"),
                        ],
                        default="NF",
                        max_length=2,
                    ),
                ),
                ("monto", models.FloatField(default=0.0)),
                ("fecha_pago", models.DateField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "pagos",
            },
        ),
        migrations.CreateModel(
            name="Expired_payments",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("penalty_fee_amount", models.FloatField()),
                (
                    "payment_user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paymentuser",
                        to="pagos.payment_user",
                    ),
                ),
            ],
            options={
                "db_table": "expired_payments",
            },
        ),
    ]
