# Generated by Django 4.1.4 on 2022-12-21 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pagos", "0002_services_users_payment_user_expired_payments"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment_user",
            name="user_id",
        ),
        migrations.DeleteModel(
            name="Expired_payments",
        ),
        migrations.DeleteModel(
            name="Payment_user",
        ),
    ]
