# Generated by Django 4.1.4 on 2022-12-21 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pagos", "0003_remove_payment_user_user_id_delete_expired_payments_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment_user",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField()),
                ("paymentDate", models.DateField(null=True)),
                ("expirationDate", models.DateField(null=True)),
                (
                    "service_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="pagos.services",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to="pagos.users",
                    ),
                ),
            ],
            options={
                "db_table": "payment_user",
            },
        ),
        migrations.CreateModel(
            name="Expired_payments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("penalty_fee_amount", models.FloatField()),
                (
                    "payment_user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paymentuser",
                        to="pagos.payment_user",
                    ),
                ),
            ],
            options={
                "db_table": "expired_payments",
            },
        ),
    ]
